=== ClusterCockpit/cc-backend/pkg/schema/schemas/job-meta.schema.json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$id": "embedfs://job-meta.schema.json",
  "title": "Job meta data",
  "description": "Meta data information of a HPC job",
  "type": "object",
  "properties": {
    "jobId": {
      "description": "The unique identifier of a job",
      "type": "integer"
    },
    "user": {
      "description": "The unique identifier of a user",
      "type": "string"
    },
    "project": {
      "description": "The unique identifier of a project",
      "type": "string"
    },
    "cluster": {
      "description": "The unique identifier of a cluster",
      "type": "string"
    },
    "subCluster": {
      "description": "The unique identifier of a sub cluster",
      "type": "string"
    },
    "partition": {
      "description": "The Slurm partition to which the job was submitted",
      "type": "string"
    },
    "arrayJobId": {
      "description": "The unique identifier of an array job",
      "type": "integer"
    },
    "numNodes": {
      "description": "Number of nodes used",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "numHwthreads": {
      "description": "Number of HWThreads used",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "numAcc": {
      "description": "Number of accelerators used",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "exclusive": {
      "description": "Specifies how nodes are shared. 0 - Shared among multiple jobs of multiple users, 1 - Job exclusive, 2 - Shared among multiple jobs of same user",
      "type": "integer",
      "minimum": 0,
      "maximum": 2
    },
    "monitoringStatus": {
      "description": "State of monitoring system during job run",
      "type": "integer"
    },
    "smt": {
      "description": "SMT threads used by job",
      "type": "integer"
    },
    "walltime": {
      "description": "Requested walltime of job in seconds",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "jobState": {
      "description": "Final state of job",
      "type": "string",
      "enum": [
        "completed",
        "failed",
        "cancelled",
        "stopped",
        "out_of_memory",
        "timeout"
      ]
    },
    "startTime": {
      "description": "Start epoch time stamp in seconds",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "duration": {
      "description": "Duration of job in seconds",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "resources": {
      "description": "Resources used by job",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "hostname": {
            "type": "string"
          },
          "hwthreads": {
            "type": "array",
            "description": "List of OS processor ids",
            "items": {
              "type": "integer"
            }
          },
          "accelerators": {
            "type": "array",
            "description": "List of of accelerator device ids",
            "items": {
              "type": "string"
            }
          },
          "configuration": {
            "type": "string",
            "description": "The configuration options of the node"
          }
        },
        "required": [
          "hostname"
        ],
        "minItems": 1
      }
    },
    "metaData": {
      "description": "Additional information about the job",
      "type": "object",
      "properties": {
        "jobScript": {
          "type": "string",
          "description": "The batch script of the job"
        },
        "jobName": {
          "type": "string",
          "description": "Slurm Job name"
        },
        "slurmInfo": {
          "type": "string",
          "description": "Additional slurm infos as show by scontrol show job"
        }
      }
    },
    "tags": {
      "description": "List of tags",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "type"
        ]
      },
      "uniqueItems": true
    },
    "statistics": {
      "description": "Job statistic data",
      "type": "object",
      "properties": {
        "mem_used": {
          "description": "Memory capacity used (required)",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "cpu_load": {
          "description": "CPU requested core utilization (load 1m) (required)",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "flops_any": {
          "description": "Total flop rate with DP flops scaled up (required)",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "mem_bw": {
          "description": "Main memory bandwidth (required)",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "net_bw": {
          "description": "Total fast interconnect network bandwidth (required)",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "file_bw": {
          "description": "Total file IO bandwidth (required)",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "ipc": {
          "description": "Instructions executed per cycle",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "cpu_user": {
          "description": "CPU user active core utilization",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "flops_dp": {
          "description": "Double precision flop rate",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "flops_sp": {
          "description": "Single precision flops rate",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "rapl_power": {
          "description": "CPU power consumption",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "acc_used": {
          "description": "GPU utilization",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "acc_mem_used": {
          "description": "GPU memory capacity used",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "acc_power": {
          "description": "GPU power consumption",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "clock": {
          "description": "Average core frequency",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "eth_read_bw": {
          "description": "Ethernet read bandwidth",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "eth_write_bw": {
          "description": "Ethernet write bandwidth",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "ic_rcv_packets": {
          "description": "Network interconnect read packets",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "ic_send_packets": {
          "description": "Network interconnect send packet",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "ic_read_bw": {
          "description": "Network interconnect read bandwidth",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "ic_write_bw": {
          "description": "Network interconnect write bandwidth",
          "$ref": "embedfs://job-metric-statistics.schema.json"
        },
        "filesystems": {
          "description": "Array of filesystems",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "type": {
                "type": "string",
                "enum": [
                  "nfs",
                  "lustre",
                  "gpfs",
                  "nvme",
                  "ssd",
                  "hdd",
                  "beegfs"
                ]
              },
              "read_bw": {
                "description": "File system read bandwidth",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "write_bw": {
                "description": "File system write bandwidth",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "read_req": {
                "description": "File system read requests",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "write_req": {
                "description": "File system write requests",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "inodes": {
                "description": "File system write requests",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "accesses": {
                "description": "File system open and close",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "fsync": {
                "description": "File system fsync",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "create": {
                "description": "File system create",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "open": {
                "description": "File system open",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "close": {
                "description": "File system close",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              },
              "seek": {
                "description": "File system seek",
                "$ref": "embedfs://job-metric-statistics.schema.json"
              }
            },
            "required": [
              "name",
              "type",
              "read_bw",
              "write_bw"
            ]
          },
          "minItems": 1
        }
      },
      "required": [
        "cpu_user",
        "cpu_load",
        "mem_used",
        "flops_any",
        "mem_bw"
      ]
    }
  },
  "required": [
    "jobId",
    "user",
    "project",
    "cluster",
    "subCluster",
    "numNodes",
    "exclusive",
    "startTime",
    "jobState",
    "duration",
    "resources",
    "statistics"
  ]
}

=== ClusterCockpit/cc-backend/test/repo/meta2.json
{"jobId":398955,"user":"k106eb10","project":"k106eb","cluster":"fritz","subCluster":"main","partition":"singlenode","arrayJobId":0,"numNodes":1,"numHwthreads":72,"numAcc":0,"exclusive":1,"monitoringStatus":1,"smt":0,"jobState":"completed","duration":260,"walltime":86340,"resources":[{"hostname":"f0720"}],"metaData":{"jobName":"ams_pipeline","jobScript":"#!/bin/bash  -l\n#SBATCH --job-name=ams_pipeline\n#SBATCH --time=23:59:00\n#SBATCH --partition=singlenode\n#SBATCH --ntasks=72\n#SBATCH --hint=multithread\n#SBATCH --chdir=/home/atuin/k106eb/k106eb10/ACE/Ni-Al/DFT/VASP_PBE_500_0.125_0.1_NM/AlNi/binaries/bulk/base-hcp/occ-shaken/hcp16.occ.4.shake.0/cfg/NiAl3NiAl11\n#SBATCH --export=NONE\nunset SLURM_EXPORT_ENV\nuss=$(whoami)\nfind /dev/shm/ -user $uss -type f -mmin +30 -delete\ncd \"/home/atuin/k106eb/k106eb10/ACE/Ni-Al/DFT/VASP_PBE_500_0.125_0.1_NM/AlNi/binaries/bulk/base-hcp/occ-shaken/hcp16.occ.4.shake.0/cfg/NiAl3NiAl11\"\nams_pipeline pipeline.json \u003e \"/home/atuin/k106eb/k106eb10/ACE/Ni-Al/DFT/VASP_PBE_500_0.125_0.1_NM/AlNi/binaries/bulk/base-hcp/occ-shaken/hcp16.occ.4.shake.0/cfg/NiAl3NiAl11/ams_pipeline_job.sh.out\" 2\u003e \"/home/atuin/k106eb/k106eb10/ACE/Ni-Al/DFT/VASP_PBE_500_0.125_0.1_NM/AlNi/binaries/bulk/base-hcp/occ-shaken/hcp16.occ.4.shake.0/cfg/NiAl3NiAl11/ams_pipeline_job.sh.err\"\n","slurmInfo":"\nJobId=398955 JobName=ams_pipeline\n   UserId=k106eb10(210387) GroupId=80111\n   Account=k106eb QOS=normal \n   Requeue=False Restarts=0 BatchFlag=True \n   TimeLimit=1439\n   SubmitTime=2023-02-09T14:11:22\n   Partition=singlenode \n   NodeList=f0720\n   NumNodes=1 NumCPUs=72 NumTasks=72 CPUs/Task=1\n   NTasksPerNode:Socket:Core=0:None:None\n   TRES_req=cpu=72,mem=250000M,node=1,billing=72\n   TRES_alloc=cpu=72,node=1,billing=72\n   Command=/home/atuin/k106eb/k106eb10/ACE/Ni-Al/DFT/VASP_PBE_500_0.125_0.1_NM/AlNi/binaries/bulk/base-hcp/occ-shaken/hcp16.occ.4.shake.0/cfg/NiAl3NiAl11/ams_pipeline_job.sh\n   WorkDir=/home/atuin/k106eb/k106eb10/ACE/Ni-Al/DFT/VASP_PBE_500_0.125_0.1_NM/AlNi/binaries/bulk/base-hcp/occ-shaken/hcp16.occ.4.shake.0/cfg/NiAl3NiAl11\n   StdErr=\n   StdOut=ams_pipeline.o%j\n"},"startTime":1675956725,"statistics":{"clock":{"unit":{"base":"Hz","prefix":"M"},"avg":2335.254,"min":800.418,"max":2734.922},"cpu_load":{"unit":{"base":""},"avg":52.72,"min":34.46,"max":71.91},"cpu_power":{"unit":{"base":"W"},"avg":407.767,"min":93.932,"max":497.636},"cpu_user":{"unit":{"base":""},"avg":63.678,"min":19.872,"max":96.633},"flops_any":{"unit":{"base":"F/s","prefix":"G"},"avg":635.672,"min":0,"max":1332.874},"flops_dp":{"unit":{"base":"F/s","prefix":"G"},"avg":261.006,"min":0,"max":382.294},"flops_sp":{"unit":{"base":"F/s","prefix":"G"},"avg":113.659,"min":0,"max":568.286},"ib_recv":{"unit":{"base":"B/s"},"avg":27981.111,"min":69.4,"max":48084.589},"ib_recv_pkts":{"unit":{"base":"packets/s"},"avg":398.939,"min":0.5,"max":693.817},"ib_xmit":{"unit":{"base":"B/s"},"avg":188.513,"min":39.597,"max":724.568},"ib_xmit_pkts":{"unit":{"base":"packets/s"},"avg":0.867,"min":0.2,"max":2.933},"ipc":{"unit":{"base":"IPC"},"avg":0.944,"min":0.564,"max":1.291},"mem_bw":{"unit":{"base":"B/s","prefix":"G"},"avg":79.565,"min":0.021,"max":116.02},"mem_power":{"unit":{"base":"W"},"avg":24.692,"min":7.883,"max":31.318},"mem_used":{"unit":{"base":"B","prefix":"G"},"avg":22.566,"min":8.225,"max":27.613},"nfs4_read":{"unit":{"base":"B/s","prefix":"M"},"avg":647,"min":0,"max":1946},"nfs4_total":{"unit":{"base":"B/s","prefix":"M"},"avg":6181.6,"min":1270,"max":11411},"nfs4_write":{"unit":{"base":"B/s","prefix":"M"},"avg":22.4,"min":11,"max":29},"vectorization_ratio":{"unit":{"base":"%"},"avg":77.351,"min":0,"max":98.837}}}
